services:
  db:
    image: postgres:15
    container_name: isw_postgres_database
    restart: always
    environment:
      POSTGRES_DB: isw_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "666"
    ports:
      - "9001:5432"
    volumes:
      - isw_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isw_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/main.js
      "

volumes:
  isw_data:
